<?php
/**
 * @file
 *
 *
 * @todo:
 * - documentation
 */

/**
 * Implements hook_menu().
 */
function stage_file_proxy_private_menu() {
  $items['admin/config/media/stage_file_proxy_private'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stage_file_proxy_private_settings_form'),
    'access arguments' => array('administer stage_file_proxy settings'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function stage_file_proxy_private_menu_alter(&$items) {
  $items['system/files']['page callback'] = 'stage_file_proxy_private_file_download_proxy';
}

/**
 * Private file proxy callback.
 */
function stage_file_proxy_private_file_download_proxy() {
  $args = func_get_args();
  // Download file to private filesystem.
  call_user_func_array('stage_file_proxy_private_download', $args);
  // Deliver as usually.
  call_user_func_array('file_download', $args);
}

/**
 * Retrieve file from external host.
 */
function stage_file_proxy_private_download() {
  $args = func_get_args();
  $scheme = array_shift($args);
  $target = implode('/', $args);
  $uri = $scheme . '://' . $target;
  $filename = array_pop($args);
  $target_dir = $scheme . '://' . implode('/', $args);

  if (file_stream_wrapper_valid_scheme($scheme) && !file_exists($uri)) {
    // Transfer file from production.
    if (!file_prepare_directory($target_dir, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
      drupal_set_message(t('Unable to create directory'), 'error');
      return FALSE;
    }
    if (!($connection = ssh2_connect(variable_get('stage_file_proxy_private_ssh_host'), variable_get('stage_file_proxy_private_ssh_port')))) {
      return FALSE;
    }
    if (!ssh2_auth_password($connection, variable_get('stage_file_proxy_private_ssh_username'), variable_get('stage_file_proxy_private_ssh_password'))) {
      return FALSE;
    }
    if (!ssh2_scp_recv($connection, variable_get('stage_file_proxy_private_ssh_remote_path') . '/' . $target, drupal_realpath($uri))) {
      return FALSE;
    }
  }
}

/**
 * Settings form.
 */
function stage_file_proxy_private_settings_form($form, &$form_state) {
  $form['stage_file_proxy_private_ssh_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Host'),
    '#default_value' => variable_get('stage_file_proxy_private_ssh_host'),
  );
  $form['stage_file_proxy_private_ssh_port'] = array(
    '#type' => 'textfield',
    '#title' => t('Port'),
    '#default_value' => variable_get('stage_file_proxy_private_ssh_port'),
  );
  $form['stage_file_proxy_private_ssh_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('stage_file_proxy_private_ssh_username'),
  );
  $form['stage_file_proxy_private_ssh_password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#default_value' => variable_get('stage_file_proxy_private_ssh_password'),
  );
  $form['stage_file_proxy_private_ssh_remote_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Remote path'),
    '#default_value' => variable_get('stage_file_proxy_private_ssh_remote_path'),
  );
  return system_settings_form($form);
}
